export enum STATES {
  NONE = 'NONE',
  CATEGORY = 'CATEGORY',
  DESCRIPTION = 'DESCRIPTION',
  PHOTO = 'PHOTO',
  MY_TICKETS = 'MY_TICKETS',
  CLOSE_TICKET = 'CLOSE_TICKET',
  DASHBOARD = 'DASHBOARD',
  PROFILE = 'PROFILE',
  ADMIN_TICKETS = 'ADMIN_TICKETS',
  ADMIN_UPDATE_STATUS = 'ADMIN_UPDATE_STATUS',
}
